# Generated by Django 3.1 on 2021-05-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=40)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
