# Generated by Django 3.1 on 2021-06-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='totalprice',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
